### ISSUE TITLE
CSRF (protection) disablement intentional?

### ISSUE THREAD

**Issue by baentsch** [admin-ch/CovidCertificate-Api-Gateway-Service#25]
After only a cursory look, is this intentional? What about adding a comment why this code creates no problem in this setup?
https://github.com/admin-ch/CovidCertificate-Api-Gateway-Service/blob/c2c44bb6980ad858fe0e3893257756e97d5531ca/src/main/java/ch/admin/bag/covidcertificate/gateway/web/config/WebSecurityConfig.java#L30-L32

**Comment by delixfe** [comment]
@baentsch Thanks for your input. Does e45300f9b0e5e91d66e2d9f04f8ac2137aa3b9bd answer your question?
